# Site Settings
title: Fahim’s Happy Place
email: sphincone@gmail.com
description: >
  How did you stumble upon here?!, this is where I write everything that comes into my mind.

baseurl: ""
url: "http://localhost:4000"
twitter_username: FahimTheTwit
github_username:  i3p9
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM