# Site Settings
title: Fahim’s Happy Place
email: sphincone@gmail.com
description: >
  Don’t know how you got here, but this is where I write everything that comes into my mind.
baseurl: “/blog“
url: "http://i3p9.github.io"
twitter_username: FahimTheTwit
github_username:  i3p9
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
